//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nix.Store.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeHistory
    {
        public int Id { get; set; }
        public string EntityName { get; set; }
        public string OriginalValue { get; set; }
        public string ChangedValue { get; set; }
        public string Action { get; set; }
        public string AgentName { get; set; }
        public System.DateTime ChangeDate { get; set; }
    }
}
