//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nix.Store.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string Type { get; set; }
        public string ItemType { get; set; }
        public string Value { get; set; }
        public string Body { get; set; }
        public int GroupId { get; set; }
        public int MapId { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual SettingMapping SettingMapping { get; set; }
    }
}
